# Generated by Django 4.0.3 on 2022-04-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_variations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variations',
            new_name='Variation',
        ),
    ]
